package com.example.eventmanagement.controller;

import com.example.eventmanagement.dto.EventRequestDTO;
import com.example.eventmanagement.dto.EventResponseDTO;
import com.example.eventmanagement.service.EventService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Tag(name = "Event Management", description = "APIs for managing events - Create, Read, Update, Delete operations. All modification operations are tracked in audit logs.")
@RestController
@RequestMapping("/events")
public class EventController {

    private final EventService eventService;

    @Autowired
    public EventController(EventService eventService) {
        this.eventService = eventService;
    }

    @PreAuthorize("hasAnyRole('SUPER_ADMIN', 'ADMIN')")
    @Operation(
            summary = "Create a new event",
            description = "Creates a new event with the provided details. The event ID and timestamps are automatically generated by the system. This action is logged in activity history."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Event created successfully", content = @Content()),
            @ApiResponse(responseCode = "400", description = "Invalid input - Validation failed (missing required fields, invalid format)", content = @Content()),
            @ApiResponse(responseCode = "403", description = "Access denied - SUPER_ADMIN or ADMIN role required", content = @Content()),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content())
    })
    @PostMapping
    public ResponseEntity<EventResponseDTO> createEvent(@Valid @RequestBody EventRequestDTO requestDTO,
                                                        HttpServletRequest request) {
        EventResponseDTO responseDTO = eventService.createEvent(requestDTO, request);
        return new ResponseEntity<>(responseDTO, HttpStatus.CREATED);
    }

    @PreAuthorize("hasAnyRole('SUPER_ADMIN', 'ADMIN', 'ATTENDEE')")
    @Operation(
            summary = "Retrieve all events",
            description = "Fetches a paginated list of all events. Use page and size parameters to control pagination. Available to all authenticated users."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Successfully retrieved list of events", content = @Content()),
            @ApiResponse(responseCode = "403", description = "Access denied - Authentication required", content = @Content()),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content())
    })
    @GetMapping
    public ResponseEntity<List<EventResponseDTO>> getAllEvents(
            @Parameter(description = "Page number (0-indexed)", example = "0")
            @RequestParam(defaultValue = "0") int page,
            @Parameter(description = "Number of items per page", example = "10")
            @RequestParam(defaultValue = "10") int size) {
        List<EventResponseDTO> events = eventService.getAllEvents(page, size);
        return new ResponseEntity<>(events, HttpStatus.OK);
    }

    @PreAuthorize("hasAnyRole('SUPER_ADMIN', 'ADMIN', 'ATTENDEE')")
    @Operation(
            summary = "Retrieve an event by ID",
            description = "Fetches a specific event by its unique identifier. Returns 404 if event not found. Available to all authenticated users."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Successfully retrieved the event", content = @Content()),
            @ApiResponse(responseCode = "403", description = "Access denied - Authentication required", content = @Content()),
            @ApiResponse(responseCode = "404", description = "Event not found - No event exists with the provided ID", content = @Content()),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content())
    })
    @GetMapping("/{id}")
    public ResponseEntity<EventResponseDTO> getEventById(
            @Parameter(description = "ID of the event to retrieve", required = true, example = "1")
            @PathVariable Long id) {
        EventResponseDTO responseDTO = eventService.getEventById(id);
        return new ResponseEntity<>(responseDTO, HttpStatus.OK);
    }

    @PreAuthorize("hasAnyRole('SUPER_ADMIN', 'ADMIN')")
    @Operation(
            summary = "Update an existing event",
            description = "Updates an event with the provided details. Event ID and createdAt timestamp remain unchanged. Only updatedAt timestamp is modified. This action is logged in activity history."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Event updated successfully", content = @Content()),
            @ApiResponse(responseCode = "400", description = "Invalid input - Validation failed", content = @Content()),
            @ApiResponse(responseCode = "403", description = "Access denied - SUPER_ADMIN or ADMIN role required", content = @Content()),
            @ApiResponse(responseCode = "404", description = "Event not found - No event exists with the provided ID", content = @Content()),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content())
    })
    @PutMapping("/{id}")
    public ResponseEntity<EventResponseDTO> updateEvent(
            @Parameter(description = "ID of the event to update", required = true, example = "1")
            @PathVariable Long id,
            @Valid @RequestBody EventRequestDTO requestDTO,
            HttpServletRequest request) {
        EventResponseDTO responseDTO = eventService.updateEvent(id, requestDTO, request);
        return new ResponseEntity<>(responseDTO, HttpStatus.OK);
    }

    @PreAuthorize("hasRole('SUPER_ADMIN')")
    @Operation(
            summary = "Delete an event",
            description = "Permanently deletes an event from the system. This action cannot be undone and is logged in activity history."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Event deleted successfully", content = @Content()),
            @ApiResponse(responseCode = "403", description = "Access denied - SUPER_ADMIN role required", content = @Content()),
            @ApiResponse(responseCode = "404", description = "Event not found - No event exists with the provided ID", content = @Content()),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content())
    })
    @DeleteMapping("/{id}")
    public ResponseEntity<String> deleteEvent(
            @Parameter(description = "ID of the event to delete", required = true, example = "1")
            @PathVariable Long id,
            HttpServletRequest request) {
        eventService.deleteEvent(id, request);
        return new ResponseEntity<>("Event deleted successfully", HttpStatus.OK);
    }
}
